databases:
  - name: noteworthy-db
    plan: free
    databaseName: noteworthy
    user: noteworthy

services:
  - type: web
    name: noteworthy
    runtime: node
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: noteworthy-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
